version: '3.9'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --cleanup --include-restarting
    restart: unless-stopped

  mysqldb:
    container_name: mysql-container
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    container_name: backend-container
    image: dani070707/ecommerce-react-backend:latest
    env_file: ./.env
    depends_on:
      - mysqldb
    ports:
      - "${NODEJS_PORT}:${NODEJS_PORT}"
    
    restart: unless-stopped

  frontend:
    container_name: frontend-container
    image: dani070707/ecommerce-react-frontend:latest
    env_file: ./.env
    depends_on:
      - backend
    ports:
      - "${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}"
   
    command: npm run dev
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
