version: '3.9'

services:
  mysqldb:
    container_name: mysql-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ecommercedb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - mysqldb
    ports:
      - "4000:4000"
    restart: always

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./frontend/.env
    depends_on:
      - mysqldb
      - backend
    ports:
      - "5174:5173"
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
