version: '3.9'

services:
  mysqldb:
    container_name: mysql-container
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./.env
    depends_on:
      - mysqldb
    ports:
      - "${NODEJS_PORT}:${NODEJS_PORT}"
    restart: always

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./.env
    depends_on:
      - backend
    ports:
      - "${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}"
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
